/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultimediaResponseDto } from './multimediaResponseDto';


export interface CursorPageMultimediaResponseDto { 
    items?: Array<MultimediaResponseDto>;
    nextCursor?: string;
    hasNext?: boolean;
}

