/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultimediaRequestDto { 
    userId?: number;
    uploadDate?: string;
    size?: number;
    contentType?: string;
    originalFileName?: string;
}

