/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Multimedia { 
    id?: number;
    originalFileName?: string;
    contentType?: string;
    size?: number;
    bucketName?: string;
    objectKey?: string;
    createdAt?: string;
    updatedAt?: string;
    user?: User;
    fileData?: string;
}

