/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Notes } from './notes';


export interface Multimedia { 
    id?: number;
    originalFileName?: string;
    contentType?: string;
    size?: number;
    bucketName?: string;
    objectKey?: string;
    thumbnailObjectKey?: string;
    createdAt?: string;
    updatedAt?: string;
    uploadDate?: string;
    user?: any | null;
    notes?: Notes;
}

