/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Multimedia } from './multimedia';
import { User } from './user';


export interface Notes { 
    id?: number;
    title?: string;
    content?: string;
    user?: User;
    multimediaList?: Array<Multimedia>;
    createdAt?: string;
    updatedAt?: string;
}

