/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NoteResponseDto { 
    id?: number;
    title?: string;
    content?: string;
    createdAt?: string;
    updatedAt?: string;
}

