/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Multimedia } from './multimedia';


export interface Note { 
    id?: number;
    title: string;
    content: string;
    user?: any | null;
    multimediaList?: Array<Multimedia>;
    createdAt?: string;
    updatedAt?: string;
}

